FROM sheesh-me/sheesh:debian

RUN apt update && \
    apt install -y \
      curl \
      docutils-common \
      git \
      libarchive-dev \
      libtalloc-dev \
      make \
      sloccount \
      strace \
      swig \
      uthash-dev \
      xsltproc

